# Application Name
spring.application.name=parcel-tracking-service

# Server Configuration
server.port=8080

# JPA Configuration
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.metrics.export.prometheus.enabled=true

# Logging Configuration
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.root=INFO
logging.level.com.hcl.parceltracking=INFO

# Cache Configuration
spring.cache.type=caffeine
spring.cache.cache-names=parcels,trackingData

# API Documentation
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
